### ISSUE TITLE
Find IMEI on SEAT MO

### ISSUE THREAD

**Issue by noiwid** [lorenzo-deluca/silence-private-server#1]
Hi,

Many thanks for this development. The idea of getting full control of our scooters is fantastic and particularly appealing with H.A. :)

I have a few questions:
- Do you have any information on how to obtain the IMEI of the SEAT-MO? The app doesn't seem to provide it.
- Where is the ASTRA Module connector located as shown in the preview?
- What cable are you using? Any reference would be appreciated!
- Is there a way to back up the previous parameters (IP/Port) before reprogramming the Astra module's IP?
- Does the ASTRA module also send the scooter GPS position ? if yes, H.A might being able to send alert when scooter moves far from it's owner! 
- Do you think the ASTRA module can directly communicate with the scooter's VOTOL controller? If that were the case, it would open the door to many other configurations (acceleration power, maximum speed of the 3 modes, choice of regenerative braking strength, etc.).

Best regards,

Benoit

**Comment by lorenzo-deluca** [comment]
Hello,
 many users have the same questions, I just now updated the README on GitHub ;)

- If you don't find IMEI no worry, at the first connection from Scooter to Server you see IMEI on server logs.
Anyway on the serial terminal you see IMEI too

- Is a null-modem RS232 cable, with a cheap RS232-USB adapter you just need to connect TX/RX and GND and open a serial terminal on your PC.

- Original parameters (for my Silence, but some users confirm also for Seat) are
SERVER: **api.connectivity.silence.eco**
PORT **38955**

- With this service we already communicate with scooter centraline ;)
You can turn ON/OFF, open Seat, honking the horn/lights... for now you cannot change driving mode..
