### ISSUE TITLE
Bike open on its own

### ISSUE THREAD

**Issue by aegina01** [lorenzo-deluca/silence-private-server#10]
Hi i have tried the command at rs232 I didn't got a response from the bike but since then the bike turns on without the key on and close in a minute. In the time that is on the engine temp is 0 and i could not ride the bike has some one any clue what is going on? I dont know if there is a way to undo if something happened.

**Comment by lorenzo-deluca** [comment]
Hello @aegina01 , mmmh, very very strange... Could you be more detailed?

**Comment by aegina01** [comment]
May I ask a question about that part of the code 

 "keepAliveInterval": 15,

That is for how often the server ask feedback from Astra?

**Comment by lorenzo-deluca** [comment]
it's for keeping the connection from astra module to your server always open, it's to make remote commands faster and to have the data updated more frequently.
anyway if you want to try to disable this feature you can put "keepAliveInterval": 0

Let me know ;)
