### ISSUE TITLE
Running the locally built image fails due to `unable to open database file`

### ISSUE THREAD

**Issue by Gclau60** [lorenzo-deluca/silence-private-server#11]
Running with the image pulled from your hub eveything works, but trying with the image built locally I get this error when running the container:
```
2024-12-01 17:50:00,771 - [silence-server] - DEBUG - Logged configured
2024-12-01 17:50:00,771 - [silence-server] - INFO - Starting Silence Server
2024-12-01 17:50:00,771 - [SilenceServerService] - INFO - Starting SilenceServerService
2024-12-01 17:50:00,772 - [SilenceServerService] - INFO - Starting DBService
2024-12-01 17:50:00,772 - [DBService] - DEBUG - DBService init
2024-12-01 17:50:00,772 - [DBService] - INFO - DBService Start
2024-12-01 17:50:00,773 - [DBService] - ERROR - Exception in MQTTService start
Traceback (most recent call last):
  File "/app/services/DBService.py", line 21, in start
    self.DBcon = sqlite3.connect('logs/silenceLOG.db', check_same_thread=False)
sqlite3.OperationalError: unable to open database file
Python version: 3.9.20
Silence-Server version: 2024.5.21
Silence-Server - Main Start
Silence-Server Main
Configuration loaded: {'IMEI': '123456567891234', 'TCPServer': {'serverPORT': *****, 'bridgeMode': True, 'silenceHOST': 'api.connectivity.silence.eco', 'silencePORT': ****, 'SaveToDB': True, 'keepAliveInterval': 15, 'BMScellVoltage_pooling_interval': 600}, 'Logging': {'LogToFile': False, 'LogLevel': 50}, 'MQTT': {'Enabled': True, 'MQTTbroker': '192.168.1.***', 'MQTTport': 1883, 'MQTTuser': '***', 'MQTTpass': '***', 'TopicPrefix': 'home/silence-server'}}
Silence-Server - Exception in main, restart...
'DBService' object has no attribute 'DBcon'
```
is the image on the dockerhub built in a different way?

**Comment by lorenzo-deluca** [comment]
Hello, 
First of all try to disable database log file SaveToDB: false in configuration file.

Let me know 🙂

**Comment by lorenzo-deluca** [comment]
seems ok, you have to wait until the scooter send data to the server.. on the trace you can see your IMEI.
You cannot see the IMEI also from original Silence/Seat app? On Silence app it was present.

**Comment by Gclau60** [comment]
I can't see IMEI from the seat mo app.
below is an extract of the serial communication....

$SHOW
{{13}}
{{10}}
************{{13}}
{{10}}
COMM Configs{{13}}
{{10}}
************{{13}}
{{10}}
$APAD,wlapn.com,astra,m2m.movistar.es,airtelwap.es,wsim{{13}}
{{10}}
$APUN,{{13}}
{{10}}
$APPW,{{13}}
{{10}}
$COPS,0{{13}}
{{10}}
$IPAD1,api.connectivity.silence.eco{{13}}
{{10}}
$MODE,6{{13}}
{{10}}
$PORT1,38955{{13}}
{{10}}
$TCPT,20,0{{13}}
{{10}}
$PROT,19,55968794727{{13}}
{{10}}
{{13}}
{{10}}
*************{{13}}
{{10}}
Other Configs{{13}}
{{10}}
*************{{13}}
{{10}}
$ACMX,35{{13}}
{{10}}
$ACMY,35{{13}}
{{10}}
$ALRM,{{13}}
{{10}}
$BLEC,1,2,100,200,7,1,65535,3,SEATMO{{13}}
{{10}}
$CANC,0,1,0,3,0{{13}}
{{10}}
$CANM,2044{{13}}
{{10}}
$CDOP,1,0{{13}}
{{10}}
$CDOP,2,0{{13}}
{{10}}
$CDIP,1,0{{13}}
{{10}}
$CLID,0,10{{13}}
{{10}}
$COLN,130{{13}}
{{10}}
$CPWR,11.5,30,5,0{{13}}
{{10}}
$DCMX,45{{13}}
{{10}}
$DCMY,45{{13}}
{{10}}
$DBUG,3,65519{{13}}
{{10}}
$DIST,5000{{13}}
{{10}}
$DRIC,0,0,0,0,0,0,30,1,0,0,0,0,0{{13}}
{{10}}
$ELEC,90,30,60{{13}}
{{10}}
$GNSS,1,1,0,0{{13}}
{{10}}
$GPSQ,50,3,5{{13}}
{{10}}
$HEAD,30{{13}}
{{10}}
$IDLE,180{{13}}
{{10}}
$IGNM,4,0{{13}}
{{10}}
$IMOS,0,0,0,0,0{{13}}
{{10}}
$IMOS,1,0,0,0,0{{13}}
{{10}}
$IMOS,2,0,0,0,0{{13}}
{{10}}
$IMOS,3,0,0,0,0{{13}}
{{10}}
$IMOS,4,0,0,0,0{{13}}
{{10}}
$GNRMC,110127.000,V,,,,,0.00,166.97,021224,,,N,V*25{{13}}
{{10}}
$IMOS,5,0,0,0,0{{13}}
{{10}}
$IMOS,6,0,0,0,0{{13}}
{{10}}
$ITIM,5{{13}}
{{10}}
$JSEC,15{{13}}
{{10}}
$LPWC,240,120,0,20{{13}}
{{10}}
$MEMS,0,0,0,0,0,5,a{{13}}
{{10}}
$MOVM,1,10{{13}}
{{10}}
$NMEA,1{{13}}
{{10}}
$ORTN,2{{13}}
{{10}}
$OSHT,30{{13}}
{{10}}
$OSIT,120{{13}}
{{10}}
$OSST,120{{13}}
{{10}}
$RATC,1,2,0{{13}}
{{10}}
$REPL,2416181701{{13}}
{{10}}
$ROAM,1{{13}}
{{10}}
$RPEC,4000,30,60{{13}}
{{10}}
$SMSL,50{{13}}
{{10}}
$SRAL,1,1,115200{{13}}
{{10}}
$STIM,10,0{{13}}
{{10}}
$STPD,60{{13}}
{{10}}
$TPEC,75,30,60{{13}}
{{10}}
$TOWP,0,0,0,0,0,0{{13}}
{{10}}
{{13}}
{{10}}
{{13}}
{{10}}
************{{13}}
{{10}}
COMM Configs{{13}}
{{10}}
************{{13}}
{{10}}
$APAD,wlapn.com,astra,m2m.movistar.es,airtelwap.es,wsim{{13}}
{{10}}
$APUN,{{13}}
{{10}}
$APPW,{{13}}
{{10}}
$COPS,0{{13}}
{{10}}
$IPAD1,api.connectivity.silence.eco{{13}}
{{10}}
$MODE,6{{13}}
{{10}}
$PORT1,38955{{13}}
{{10}}
$TCPT,20,0{{13}}
{{10}}
$PROT,19,55968794727{{13}}
{{10}}
{{13}}
{{10}}
*************{{13}}
{{10}}
Other Configs{{13}}
{{10}}
*************{{13}}
{{10}}
$ACMX,35{{13}}
{{10}}
$ACMY,35{{13}}
{{10}}
$ALRM,{{13}}
{{10}}
$BLEC,1,2,100,200,7,1,65535,3,SEATMO{{13}}
{{10}}
$CANC,0,1,0,3,0{{13}}
{{10}}
$CANM,2044{{13}}
{{10}}
$CDOP,1,0{{13}}
{{10}}
$CDOP,2,0{{13}}
{{10}}
$CDIP,1,0{{13}}
{{10}}
$CLID,0,10{{13}}
{{10}}
$COLN,130{{13}}
{{10}}
$CPWR,11.5,30,5,0{{13}}
{{10}}
$DCMX,45{{13}}
{{10}}
$DCMY,45{{13}}
{{10}}
$DBUG,3,65519{{13}}
{{10}}
$DIST,5000{{13}}
{{10}}
$DRIC,0,0,0,0,0,0,30,1,0,0,0,0,0{{13}}
{{10}}
$ELEC,90,30,60{{13}}
{{10}}
$GNSS,1,1,0,0{{13}}
{{10}}
$GPSQ,50,3,5{{13}}
{{10}}
$HEAD,30{{13}}
{{10}}
$IDLE,180{{13}}
{{10}}
$IGNM,4,0{{13}}
{{10}}
$IMOS,0,0,0,0,0{{13}}
{{10}}
$IMOS,1,0,0,0,0{{13}}
{{10}}
$IMOS,2,0,0,0,0{{13}}
{{10}}
$IMOS,3,0,0,0,0{{13}}
{{10}}
$IMOS,4,0,0,0,0{{13}}
{{10}}
$IMOS,5,0,0,0,0{{13}}
{{10}}
$IMOS,6,0,0,0,0{{13}}
{{10}}
$ITIM,5{{13}}
{{10}}
$JSEC,15{{13}}
{{10}}
$LPWC,240,120,0,20{{13}}
{{10}}
$MEMS,0,0,0,0,0,5,a{{13}}
{{10}}
$MOVM,1,10{{13}}
{{10}}
$NMEA,1{{13}}
{{10}}
$ORTN,2{{13}}
{{10}}
$OSHT,30{{13}}
{{10}}
$OSIT,120{{13}}
{{10}}
$OSST,120{{13}}
{{10}}
$RATC,1,2,0{{13}}
{{10}}
$REPL,2416181701{{13}}
{{10}}
$ROAM,1{{13}}
{{10}}
$RPEC,4000,30,60{{13}}
{{10}}
$SMSL,50{{13}}
{{10}}
$SRAL,1,1,115200{{13}}
{{10}}
$STIM,10,0{{13}}
{{10}}
$STPD,60{{13}}
{{10}}
$TPEC,75,30,60{{13}}
{{10}}
$TOWP,0,0,0,0,0,0{{13}}
{{10}}
{{13}}
{{10}}
$GNRMÃ,UN{{13}}
{{10}}
$SHOWShH,UN{{13}}
{{10}}
Ext Volts: 12.05V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
$GNRMC,110128.000,V,,,,,0.00,166.97,021224,,,N,V*2A{{13}}
{{10}}
$GNRMC,110129.000,V,,,,,0.00,166.97,021224,,,N,V*2B{{13}}
{{10}}
$GNRMC,110130.000,V,,,,,0.00,166.97,021224,,,N,V*23{{13}}
{{10}}
0 SMS to handle{{13}}
{{10}}
$GNRMC,110131.000,V,,,,,0.00,166.97,021224,,,N,V*22{{13}}
{{10}}
$GPRSSI,22{{13}}
{{10}}
$GNRMC,110132.000,V,,,,,0.00,166.97,021224,,,N,V*21{{13}}
{{10}}
Ext Volts: 12.05V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
$GNRMC,110133.000,V,,,,,0.00,166.97,021224,,,N,V*20{{13}}
{{10}}
$GNRMC,110134.000,V,,,,,0.00,166.97,021224,,,N,V*27{{13}}
{{10}}
$GNRMC,110135.000,V,,,,,0.00,166.97,021224,,,N,V*26{{13}}
{{10}}
$GNRMC,110136.000,V,,,,,0.00,166.97,021224,,,N,V*25{{13}}
{{10}}
$GNRMC,110137.000,V,,,,,0.00,166.97,021224,,,N,V*24{{13}}
{{10}}
Ext Volts: 12.04V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
$GNRMC,110138.000,V,,,,,0.00,166.97,021224,,,N,V*2B{{13}}
{{10}}
$GNRMC,110139.000,V,,,,,0.00,166.97,021224,,,N,V*2A{{13}}
{{10}}
$GNRMC,110140.000,V,,,,,0.00,166.97,021224,,,N,V*24{{13}}
{{10}}
$GNRMC,110141.000,V,,,,,0.00,166.97,021224,,,N,V*25{{13}}
{{10}}
$GNRMC,110142.000,V,,,,,0.00,166.97,021224,,,N,V*26{{13}}
{{10}}
Ext Volts: 12.05V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
$GNRMC,110143.000,V,,,,,0.00,166.97,021224,,,N,V*27{{13}}
{{10}}
$GNRMC,110144.000,V,,,,,0.00,166.97,021224,,,N,V*20{{13}}
{{10}}
$GNRMC,110145.000,V,,,,,0.00,166.97,021224,,,N,V*21{{13}}
{{10}}
$GNRMC,110146.000,V,,,,,0.00,166.97,021224,,,N,V*22{{13}}
{{10}}
$GNRMC,110147.000,V,,,,,0.00,166.97,021224,,,N,V*23{{13}}
{{10}}
Ext Volts: 12.05V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
$GNRMC,110148.000,V,,,,,0.00,166.97,021224,,,N,V*2C{{13}}
{{10}}
$GNRMC,110149.000,V,,,,,0.00,166.97,021224,,,N,V*2D{{13}}
{{10}}
$GNRMC,110150.000,V,,,,,0.00,166.97,021224,,,N,V*25{{13}}
{{10}}
$GNRMC,110151.000,V,,,,,0.00,166.97,021224,,,N,V*24{{13}}
{{10}}
$GNRMC,110152.000,V,,,,,0.00,166.97,021224,,,N,V*27{{13}}
{{10}}
Ext Volts: 12.04V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
$GNRMC,110153.000,V,,,,,0.00,166.97,021224,,,N,V*26{{13}}
{{10}}
$GNRMC,110154.000,V,,,,,0.00,166.97,021224,,,N,V*21{{13}}
{{10}}
$GNRMC,110155.000,V,,,,,0.00,166.97,021224,,,N,V*20{{13}}
{{10}}
$GNRMC,110156.000,V,,,,,0.00,166.97,021224,,,N,V*23{{13}}
{{10}}
S01 MANUAL PWR OFF (KEY){{13}}
{{10}}
$GNRMC,110157.000,V,,,,,0.00,166.97,021224,,,N,V*22{{13}}
{{10}}
S01 STATUS CHANGED TO: 2{{13}}
{{10}}
S01 IGN ON{{13}}
{{10}}
IGN ON event{{13}}
{{10}}
S01 0x321 ECU PWR OFF INHIBIT for 30 seconds{{13}}
{{10}}
S01 Query IDs{{13}}
{{10}}
GPS no valid fix timeout - recover GPS{{13}}
{{10}}
GPS power off for 2500 msecs{{13}}
{{10}}
Battery ID: 445043973{{13}}
{{10}}
BMS Sigfox ID (8): {{13}}
{{10}}
Sigfox CAN hex:00 00 00 00 00 00 00 00 {{13}}
{{10}}
Silence Frame 0x31C: 02 55 43 59 53 30 31 53 {{13}}
{{10}}
REPORT REASON(S):{{13}}
{{10}}
 TIMED{{13}}
{{10}}
 JNY START{{13}}
{{10}}
STATUS:{{13}}
{{10}}
 IGN ON{{13}}
{{10}}
 GPS INVALID{{13}}
{{10}}
Sending Report to comm_task{{13}}
{{10}}
       msn: 125{{13}}
{{10}}
     jtime: 1417172518{{13}}
{{10}}
Silence Frame 0x31C: 03 32 5A 50 42 30 30 30 {{13}}
{{10}}
      time: 11:01:58{{13}}
{{10}}
      date: 02:12:2024{{13}}
{{10}}
       lat: 45.812144{{13}}
{{10}}
       lon: 10.029083{{13}}
{{10}}
      head: 247.0 degrees{{13}}
{{10}}
       spd: 4.3 kmh{{13}}
{{10}}
      sats: 4{{13}}
{{10}}
      pdop: 2.16{{13}}
{{10}}
  est. err: 31 m{{13}}
{{10}}
     accel: x:101  y:0  z:98  m/s/s * 10{{13}}
{{10}}
     decel: x:0  y:14  z:0  m/s/s * 10{{13}}
{{10}}
Ext Volts: 12.04V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
Silence Frame 0x31C: 04 33 38 37 00 00 00 00 {{13}}
{{10}}
Silence Frame ID: UCYS01S2ZPB000387{{13}}
{{10}}
Writing nv{{13}}
{{10}}
SCUTUM Query BMS ID{{13}}
{{10}}
SCUTUM Query ECU ID{{13}}
{{10}}
S01 ECU UID M: 1e8019{{13}}
{{10}}
S01 ECU UID H: 6c01000b{{13}}
{{10}}
1 reports in FFS{{13}}
{{10}}
Report to send:{{13}}
{{10}}
S01 ECU UID L: 24194e45{{13}}
{{10}}
msn: 125  time: 1417172518  lat: 45.812144  lon: 10.029083  more: 0{{13}}
{{10}}
SCUTUM Query ECU FW Ver{{13}}
{{10}}
STM ECU FW Git HASH 96 C9 FE 95 A6 45 27 EE AA 1E C9 00 3D 8A F8 02 48 12 02 71 {{13}}
{{10}}
QISTATE mode: TCP, hostname: 35.205.173.15{{13}}
{{10}}
report socket (0) connected{{13}}
{{10}}
SCUTUM S01:5F 08 08 02 3B FF F0 1A 86 D5 05 00 00 00 5A 00 AA 00 62 00 00 00 00 00 0F A8 71 00 01 89 89 00 0F 88 A6 0B 02 00 00 11 D2 00 00 00 00 00 {{13}}
{{10}}
SCUTUM Query BMS FW Ver{{13}}
{{10}}
STM BMS FW Git HASH 3F A2 AF 7F F8 99 4E 11 12 B9 79 FD 83 0E FA 05 81 A4 F0 11 {{13}}
{{10}}
Ext Volts: 12.04V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
S01 PWR OFF{{13}}
{{10}}
SCUTUM Query Energy Stats{{13}}
{{10}}
SCUTUM CAN TX SUPPRESSED [0x1B0] - IN PROCESS OF POWERING OFF...{{13}}
{{10}}
SCUTUM CAN TX SUPPRESSED [0x1B1] - IN PROCESS OF POWERING OFF...{{13}}
{{10}}
94 bytes sent{{13}}
{{10}}
REPORT REASON(S):{{13}}
{{10}}
 SCUTUM{{13}}
{{10}}
STATUS:{{13}}
{{10}}
 IGN ON{{13}}
{{10}}
 GPS INVALID{{13}}
{{10}}
Sending Report to comm_task{{13}}
{{10}}
       msn: 126{{13}}
{{10}}
     jtime: 1417172519{{13}}
{{10}}
      time: 11:01:59{{13}}
{{10}}
      date: 02:12:2024{{13}}
{{10}}
       lat: 45.812144{{13}}
{{10}}
       lon: 10.029083{{13}}
{{10}}
      head: 247.0 degrees{{13}}
{{10}}
       spd: 4.3 kmh{{13}}
{{10}}
      sats: 4{{13}}
{{10}}
      pdop: 2.16{{13}}
{{10}}
  est. err: 31 m{{13}}
{{10}}
     accel: x:0  y:0  z:0  m/s/s * 10{{13}}
{{10}}
     decel: x:0  y:0  z:0  m/s/s * 10{{13}}
{{10}}
Ext Volts: 12.04V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
Writing nv{{13}}
{{10}}
MODEM URC: [+QIURC: "recv",0,1]{{13}}
{{10}}
Socket 0 has 1 bytes pending{{13}}
{{10}}
Session 0, 1 bytes buffered; socket_data[1,0,0,0,0]{{13}}
{{10}}
Received 1 bytes from report socket{{13}}
{{10}}
ACK{{13}}
{{10}}
Deleting 1 reports{{13}}
{{10}}
1 reports in FFS{{13}}
{{10}}
Report to send:{{13}}
{{10}}
msn: 126  time: 1417172519  lat: 45.812144  lon: 10.029083  more: 0{{13}}
{{10}}
QISTATE mode: TCP, hostname: 35.205.173.15{{13}}
{{10}}
report socket (0) connected{{13}}
{{10}}
SCUTUM S01:5F 08 08 02 3B FF FB 1A 86 D5 05 00 00 00 00 00 00 00 62 00 00 00 00 00 0F A8 71 00 01 89 89 00 0F 88 A6 0B 02 00 00 11 D2 00 00 00 00 00 {{13}}
{{10}}
SCUTUM UIDS:55 43 59 53 30 31 53 32 5A 50 42 30 30 30 33 38 37 45 4E 19 24 19 80 1E 00 0B 00 01 6C 96 C9 FE 95 A6 45 27 EE AA 1E C9 00 3D 8A F8 02 48 12 02 71 1A 86 D5 05 11 00 02 80 43 73 45 4E D1 AC CD CC 3F A2 AF 7F F8 99 4E 11 12 B9 79 FD 83 0E FA 05 81 A4 F0 11 00 00 00 00 00 00 00 00 4E 4F 54 5F 53 54 4F 52 45 44 00 00 00 {{13}}
{{10}}
200 bytes sent{{13}}
{{10}}
MODEM URC: [+QIURC: "recv",0,1]{{13}}
{{10}}
Socket 0 has 1 bytes pending{{13}}
{{10}}
Session 0, 1 bytes buffered; socket_data[1,0,0,0,0]{{13}}
{{10}}
Received 1 bytes from report socket{{13}}
{{10}}
ACK{{13}}
{{10}}
Deleting 1 reports{{13}}
{{10}}
$GNRMC,110201.515,V,,,,,0.00,0.00,021224,,,N,V*2C{{13}}
{{10}}
REPORT REASON(S):{{13}}
{{10}}
 CANBUS{{13}}
{{10}}
STATUS:{{13}}
{{10}}
 IGN ON{{13}}
{{10}}
 GPS INVALID{{13}}
{{10}}
Report suppressed, according to REPL{{13}}
{{10}}
Ext Volts: 12.03V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
SCUTUM Query Energy Stats{{13}}
{{10}}
SCUTUM CAN TX SUPPRESSED [0x1B0] - IN PROCESS OF POWERING OFF...{{13}}
{{10}}
SCUTUM CAN TX SUPPRESSED [0x1B1] - IN PROCESS OF POWERING OFF...{{13}}
{{10}}
$GNRMC,110203.755,V,,,,,0.00,0.00,021224,,,N,V*28{{13}}
{{10}}
$GNRMC,110204.755,V,,,,,0.00,0.00,021224,,,N,V*2F{{13}}
{{10}}
$GNRMC,110205.755,V,,,,,0.00,0.00,021224,,,N,V*2E{{13}}
{{10}}
GPS_EVENT_TTFF - 0s{{13}}
{{10}}
$GNRMC,110206.755,V,,,,,0.00,0.00,021224,,,N,V*2D{{13}}
{{10}}
$GNRMC,110207.755,V,,,,,0.00,0.00,021224,,,N,V*2C{{13}}
{{10}}
Ext Volts: 12.01V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
SCUTUM Query Energy Stats{{13}}
{{10}}
SCUTUM CAN TX SUPPRESSED [0x1B0] - IN PROCESS OF POWERING OFF...{{13}}
{{10}}
SCUTUM CAN TX SUPPRESSED [0x1B1] - IN PROCESS OF POWERING OFF...{{13}}
{{10}}
$GNRMC,110208.755,V,,,,,0.00,0.00,021224,,,N,V*23{{13}}
{{10}}
$GNRMC,110209.755,V,,,,,0.00,0.00,021224,,,N,V*22{{13}}
{{10}}
$GNRMC,110210.755,V,,,,,0.00,0.00,021224,,,N,V*2A{{13}}
{{10}}
$GNRMC,110211.755,V,,,,,0.00,0.00,021224,,,N,V*2B{{13}}
{{10}}
REPORT REASON(S):{{13}}
{{10}}
 TIMED{{13}}
{{10}}
STATUS:{{13}}
{{10}}
 IGN ON{{13}}
{{10}}
 GPS INVALID{{13}}
{{10}}
Sending Report to comm_task{{13}}
{{10}}
       msn: 127{{13}}
{{10}}
     jtime: 1417172534{{13}}
{{10}}
      time: 11:02:14{{13}}
{{10}}
      date: 02:12:2024{{13}}
{{10}}
       lat: 45.812144{{13}}
{{10}}
       lon: 10.029083{{13}}
{{10}}
      head: 247.0 degrees{{13}}
{{10}}
       spd: 4.3 kmh{{13}}
{{10}}
      sats: 4{{13}}
{{10}}
      pdop: 2.16{{13}}
{{10}}
  est. err: 31 m{{13}}
{{10}}
     accel: x:100  y:0  z:98  m/s/s * 10{{13}}
{{10}}
     decel: x:0  y:13  z:0  m/s/s * 10{{13}}
{{10}}
Ext Volts: 12.01V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
Writing nv{{13}}
{{10}}
1 reports in FFS{{13}}
{{10}}
Report to send:{{13}}
{{10}}
msn: 127  time: 1417172534  lat: 45.812144  lon: 10.029083  more: 0{{13}}
{{10}}
QISTATE mode: TCP, hostname: 35.205.173.15{{13}}
{{10}}
report socket (0) connected{{13}}
{{10}}
SCUTUM S01:5F 08 08 02 3B FF FD 1A 86 D5 05 40 00 00 64 00 A0 00 62 00 00 00 00 00 0F A8 71 00 01 89 89 00 0F 88 A6 0E 02 00 00 11 D2 00 00 00 00 00 {{13}}
{{10}}
$GNRMC,110212.755,V,,,,,0.00,0.00,021224,,,N,V*28{{13}}
{{10}}
Ext Volts: 12.03V{{13}}
{{10}}
Batt: 4.15V / 93%, NOT Charging{{13}}
{{10}}
SCUTUM Query Energy Stats{{13}}
{{10}}
94 bytes sent{{13}}
{{10}}
MODEM URC: [+QIURC: "recv",0,1]{{13}}
{{10}}
Socket 0 has 1 bytes pending{{13}}
{{10}}
Session 0, 1 bytes buffered; socket_data[1,0,0,0,0]{{13}}
{{10}}
Received 1 bytes from report socket{{13}}
{{10}}
ACK{{13}}
{{10}}

puo essere questo?
Silence Frame ID: UCYS01S2ZPB000387

**Comment by lorenzo-deluca** [comment]
I don't think so.. anyway, seems you've configured the old silence server "$IPAD1,api.connectivity.silence.eco{{13}}"
So, the scooter send data to silence server, not your private server...

**Comment by Gclau60** [comment]
I indicated that to you because the value of B000387 is shown in the VIN item in the dealership coupon report.....

**Comment by Gclau60** [comment]
I now found in the seat mo manual that the win code is exactly this.
UCYS01S2ZPB000387

**Comment by lorenzo-deluca** [comment]
ok, good.. but anyway if the module is properly config you can see the IMEI from server logs... does the module connect to your server?
