### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by aegina01** [lorenzo-deluca/silence-private-server#2]
hi i have install the server on docker but how can i configure the json file with my IMEI and MQTT, i could not find a way to open the configuration.json 
![Στιγμιότυπο οθόνης (3)](https://github.com/user-attachments/assets/a90d205d-5d29-4aa0-a55e-84b8c2a73427)

**Comment by lorenzo-deluca** [comment]
Hello @aegina01, you have to create a configuration.json and map it into container.

![image](https://github.com/user-attachments/assets/74e84662-1401-4f28-a0af-957bbcc64545)

Let me know if it works 👍
