### ISSUE TITLE
OBD pinout

### ISSUE THREAD

**Issue by kytu282** [lorenzo-deluca/silence-private-server#3]
Hello, first of all, congratulations for the project.
I have been trying to connect to the Astra module through the OBD port of the motorcycle, following the instructions, but I had not achieved anything, no communication,Finally, by changing pins 2 and 3 (exchange between them) I have managed to receive communication with the motorcycle, the Astra module is continuously talking, gives GPS information, battery status, etc
Could we check the pinout? My motorcycle is one of the first 500 units
I have made an OBD to DB9 adapter, to facilitate the connection.
In any case, I have not been able to get the Astra module to read the commands that I send it, to change the server, I have had to do it by SMS with my own SIM, which has communicated without problem with the Silence server 

![IMG_20240718_195953.jpg](https://github.com/user-attachments/assets/1009dde7-55d1-46e7-9767-b3672ce13ed2)

![IMG_20240718_200142.jpg](https://github.com/user-attachments/assets/7ced2a8a-a3dd-4c1a-9597-d91e67730c23)

**Comment by noiwid** [comment]
Hi, thanks for your feedback. 
What's the reference of the plug you bought/tweak?

**Comment by lorenzo-deluca** [comment]
Hello, so let me understand, if you open a terminal on the mapped COM with the settings written down you don't see any message? If I remember correctly by default on my scooter it sends several debug messages.

I don't think they changed the pinout of the ODB port anyway turning TX and RX is standard 👍

**Comment by kytu282** [comment]
> Hi, thanks for your feedback. 
> What's the reference of the plug you bought/tweak?

It is a generic OBD connector, I bought it on Amazon, but you can find it anywhere, I had the DB9 at home

**Comment by kytu282** [comment]
> Hi, thanks for your feedback. 
> What's the reference of the plug you bought/tweak?

It is a generic OBD connector, I bought it on Amazon, but you can find it anywhere, I had the DB9 at home

**Comment by kytu282** [comment]
> Hello, so let me understand, if you open a terminal on the mapped COM with the settings written down you don't see any message? If I remember correctly by default on my scooter it sends several debug messages.
> 
> I don't think they changed the pinout of the ODB port anyway turning TX and RX is standard 👍 
> 
> 

If I connect it the same as in your diagram, I have no communication, if I exchange pins 2 and 3, communication takes place without problem.
You can verify in the photo, as my cables are, it works on my motorcycle, although I don't have any other motorcycles to verify.

**Comment by lorenzo-deluca** [comment]
Hello @kytu282 , news? Are you able now to connect to Astra module?

**Comment by kytu282** [comment]
Yes, I was able to connect by reversing the pins, I don't know of anyone else who has had the same problem, perhaps only the first 500 units, or my motorcycle, which was assembled incorrectly, now I have the problem with making the server, I tried to use Flespi, but it is not compatible with the Astra and I don't know where to start doing it 😅

**Comment by lorenzo-deluca** [comment]
mmmh, for server you have to build my Docker..! On a Raspberry, NAS, PC, etc... 
Of course, it must always be accessible and you must do port-forwarding as indicated in the documentation.
