### ISSUE TITLE
RS232 to USB

### ISSUE THREAD

**Issue by sugar012** [lorenzo-deluca/silence-private-server#4]
Ho to all. Is this 232 to ttl suitable for the job ? Of course connected via USB

![Screenshot_2024-07-23-22-18-36-431_com amazon mShop android shopping-edit](https://github.com/user-attachments/assets/972dc61f-6adb-4514-9415-e6362d26dc3f)

**Comment by noiwid** [comment]
hello, 
on my side I've used this combinaison of items:
![61w8V5GeCwL __AC_SX300_SY300_QL70_ML2_](https://github.com/user-attachments/assets/9365c89d-1614-4b2c-9881-4fc8b335d222)
![téléchargement (1)](https://github.com/user-attachments/assets/202ed398-7b2b-41ff-8f87-5d7bacb2af0c)
![téléchargement](https://github.com/user-attachments/assets/46bec88c-b343-4d7e-b800-4016d7c8a323)

**Comment by sugar012** [comment]
> hello, on my side I've used this combinaison of items: ![61w8V5GeCwL _AC_SX300_SY300_QL70_ML2](https://private-user-images.githubusercontent.com/22593155/351725342-9365c89d-1614-4b2c-9881-4fc8b335d222.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzE5NjQsIm5iZiI6MTcyMjA3MTY2NCwicGF0aCI6Ii8yMjU5MzE1NS8zNTE3MjUzNDItOTM2NWM4OWQtMTYxNC00YjJjLTk4ODEtNGZjOGIzMzVkMjIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA5MTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYjZkZWUxYWNkY2Q4NGNmZTQwMjU5NGQwNWU0MzU2MDk1ZGRjYTA0MzU5MjM1MzA5MWY1ZGViZjJlYzBhMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4GCqQpTDDa5O3rN_GT45mAU8v0FXHJJ1o-_-42PMDYc) ![téléchargement (1)](https://private-user-images.githubusercontent.com/22593155/351725349-202ed398-7b2b-41ff-8f87-5d7bacb2af0c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzE5NjQsIm5iZiI6MTcyMjA3MTY2NCwicGF0aCI6Ii8yMjU5MzE1NS8zNTE3MjUzNDktMjAyZWQzOTgtN2IyYi00MWZmLThmODctNWQ3YmFjYjJhZjBjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwOTE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjFhN2I0NmJiZjM3NTUxZTdjZDRlM2NhNDExMjMwN2ViYzcwZmQzYjg4YzYxMzg1Y2RkMzgyYzcwYTJiODIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EjXKNEmJbIIaA2zcJzxg0vo96pVINsxYhEmFmAThe8c) ![téléchargement](https://private-user-images.githubusercontent.com/22593155/351725352-46bec88c-b343-4d7e-b800-4016d7c8a323.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzE5NjQsIm5iZiI6MTcyMjA3MTY2NCwicGF0aCI6Ii8yMjU5MzE1NS8zNTE3MjUzNTItNDZiZWM4OGMtYjM0My00ZDdlLWI4MDAtNDAxNmQ3YzhhMzIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwOTE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjU3M2E2MGQzN2RjZGQ1MmU5ZDJlNTE5NmI4ZDQ2OTJkMjgyODYwNGEyMGFmYjJjZDE3NzNiNGJiZTgwOGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.paFMV-DRgd6LCSyiuwp-_fyXS1sw1FitDYDB66yYhlk)

Ok, i got the same usb-rs232 cable as you. it's the first time i work with terminal so i'm a little lost here. Is this correct?
![image](https://github.com/user-attachments/assets/840b5fcf-0904-45f8-ae4f-ed724f8bd7c6)

**Comment by lorenzo-deluca** [comment]
Hello, check the GND connection to serial port.. have you already try to reverse TX and RX pins?

Let me know ;)

**Comment by sugar012** [comment]
> Hello, check the GND connection to serial port.. have you already try to reverse TX and RX pins?
> 
> Let me know ;)

by swapping i got this. Also settings are 8,1, none and none
![image](https://github.com/user-attachments/assets/74a580c7-f88f-4cc2-acf8-f7a16607af5f)

**Comment by lorenzo-deluca** [comment]
It seems bad serial pin connection.. double check GND and try to revert TX and RX.

**Comment by sugar012** [comment]
> It seems bad serial pin connection.. double check GND and try to revert TX and RX.

What should the output be like? do you have telegram? Sono italiano cmq

**Comment by sugar012** [comment]
> It seems bad serial pin connection.. double check GND and try to revert TX and RX.

i swapped GND and TX .. sorry. but it wont connect to the server. port should be open

![image](https://github.com/user-attachments/assets/bf3e747c-d823-4184-b0ae-1457bdedd899)

**Comment by sugar012** [comment]
i had to tick this box 
![image](https://github.com/user-attachments/assets/183e58c1-6784-4e62-b909-3544cc9d0ea9)

**Comment by sugar012** [comment]
Hello Lorenzo. I'm maybe at 90%. i can run che python scrypt only without the logger and sql database. i guess that cell voltages nee the db to be showed up in HA?

```
alpine-docker:~/silence-private-server# python silence-server.py 
Python version: 3.12.3
Silence-Server version: 2024.5.21
Silence-Server - Main Start
Silence-Server Main
Configuration loaded: {'IMEI': 'zzz', 'TCPServer': {'serverPORT': 38955, 'bridgeMode': True, 'silenceHOST': 'api.connectivity.silence.eco', 'silencePORT': 38955, 'SaveToDB': True, 'keepAliveInterval': 15, 'BMScellVoltage_pooling_interval': 600}, 'Logging': {'LogToFile': False, 'LogLevel': 50}, 'MQTT': {'Enabled': True, 'MQTTbroker': '192.168.2.30', 'MQTTport': 1883, 'MQTTuser': 'mqtt', 'MQTTpass': 'AGw&!e*CF7DJ9u', 'TopicPrefix': 'home/silence-server'}}
2024-07-27 15:46:42,625 - [silence-server] - DEBUG - Logged configured
2024-07-27 15:46:42,626 - [silence-server] - INFO - Starting Silence Server
2024-07-27 15:46:42,626 - [SilenceServerService] - INFO - Starting SilenceServerService
2024-07-27 15:46:42,626 - [SilenceServerService] - INFO - Starting DBService
2024-07-27 15:46:42,626 - [DBService] - DEBUG - DBService init
2024-07-27 15:46:42,626 - [DBService] - INFO - DBService Start
2024-07-27 15:46:42,626 - [DBService] - ERROR - Exception in MQTTService start
Traceback (most recent call last):
  File "/root/silence-private-server/services/DBService.py", line 21, in start
    self.DBcon = sqlite3.connect('logs/silenceLOG.db', check_same_thread=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
Silence-Server - Exception in main, restart...
'DBService' object has no attribute 'DBcon'
```
and with the logger active:

```
alpine-docker:~/silence-private-server# python silence-server.py 
Python version: 3.12.3
Silence-Server version: 2024.5.21
Silence-Server - Main Start
Silence-Server Main
Configuration loaded: {'IMEI': 'zzz', 'TCPServer': {'serverPORT': 38955, 'bridgeMode': True, 'silenceHOST': 'api.connectivity.silence.eco', 'silencePORT': 38955, 'SaveToDB': False, 'keepAliveInterval': 15, 'BMScellVoltage_pooling_interval': 600}, 'Logging': {'LogToFile': True, 'LogLevel': 50}, 'MQTT': {'Enabled': True, 'MQTTbroker': '192.168.2.30', 'MQTTport': 1883, 'MQTTuser': 'mqtt', 'MQTTpass': 'AGw&!e*CF7DJ9u', 'TopicPrefix': 'home/silence-server'}}
Silence-Server - Exception in main, restart...
[Errno 2] No such file or directory: '/root/silence-private-server/logs/silence-server.log'
alpine-docker:~/silence-private-server# 
```

**Comment by lorenzo-deluca** [comment]
sorry, my fault in the default configuration.json, put 

``yaml
"LogToFile": false

**Comment by sugar012** [comment]
Ok, and what about the database? the cell voltage seems to be not working also?

`2024-07-27 16:09:03,096 - [MQTTService] - DEBUG - Publishing scooter status: {'status': {'value': 0.0, 'MQTT_topic': 'status'}, 'movementAlarm': {'value': 0, 'MQTT_topic': 'movementAlarm'}, 'batteryIn': {'value': 1, 'MQTT_topic': 'batteryIn'}, 'astraBatterySOC': {'value': 98.0, 'MQTT_topic': 'astraBatterySOC'}, 'latitude': {'value': xxx, 'MQTT_topic': 'latitude'}, 'longitude': {'value': xxx, 'MQTT_topic': 'longitude'}, 'batterySOC': {'value': 99.0, 'MQTT_topic': 'SOCbatteria'}, 'batteryTempMax': {'value': 32.0, 'MQTT_topic': 'BatteryTempMax'}, 'batteryTempMin': {'value': 31.0, 'MQTT_topic': 'BatteryTempMin'}, 'batteryVoltage': {'value': 57.6, 'MQTT_topic': 'VOLTbatteria'}, 'batteryCurrent': {'value': 0.0, 'MQTT_topic': 'batteryCurrent'}, 'motorTemp': {'value': 'None', 'MQTT_topic': 'motorTemp'}, 'inverterTemp': {'value': 'None', 'MQTT_topic': 'inverterTemp'}, 'speed': {'value': 'None', 'MQTT_topic': 'speed'}, 'range': {'value': 102.0, 'MQTT_topic': 'range'}, 'chargedEnergy': {'value': 327.1, 'MQTT_topic': 'chargedEnergy'}, 'RegeneratedEnergy': {'value': 24.128611111111113, 'MQTT_topic': 'RegeneratedEnergy'}, 'DischargedEnergy': {'value': 317.15527777777777, 'MQTT_topic': 'DischargedEnergy'}, 'ambientTemp': {'value': 'None', 'MQTT_topic': 'ambientTemp'}, 'odo': {'value': 4469.0, 'MQTT_topic': 'odo'}, 'VIN': {'value': None, 'MQTT_topic': 'VIN'}, 'Cell1Voltage': {'value': None, 'MQTT_topic': 'Cell1Voltage'}, 'Cell2Voltage': {'value': None, 'MQTT_topic': 'Cell2Voltage'}, 'Cell3Voltage': {'value': None, 'MQTT_topic': 'Cell3Voltage'}, 'Cell4Voltage': {'value': None, 'MQTT_topic': 'Cell4Voltage'}, 'Cell5Voltage': {'value': None, 'MQTT_topic': 'Cell5Voltage'}, 'Cell6Voltage': {'value': None, 'MQTT_topic': 'Cell6Voltage'}, 'Cell7Voltage': {'value': None, 'MQTT_topic': 'Cell7Voltage'}, 'Cell8Voltage': {'value': None, 'MQTT_topic': 'Cell8Voltage'}, 'Cell9Voltage': {'value': None, 'MQTT_topic': 'Cell9Voltage'}, 'Cell10Voltage': {'value': None, 'MQTT_topic': 'Cell10Voltage'}, 'Cell11Voltage': {'value': None, 'MQTT_topic': 'Cell11Voltage'}, 'Cell12Voltage': {'value': None, 'MQTT_topic': 'Cell12Voltage'}, 'Cell13Voltage': {'value': None, 'MQTT_topic': 'Cell13Voltage'}, 'Cell14Voltage': {'value': None, 'MQTT_topic': 'Cell14Voltage'}}`

**Comment by lorenzo-deluca** [comment]
good, very well done! :)
cell voltages is valued only when scooter inverter is ON. have you try to travel?

**Comment by sugar012** [comment]
> good, very well done! :) cell voltages is valued only when scooter inverter is ON. have you try to travel?

yep, as soon as i switched it on (remotely of course :)) all mqqt are published.
One last thing, i hope. Where do you think this "none" got in the way instead of "silence" ?

![image](https://github.com/user-attachments/assets/c974593c-eb2e-44a6-9528-4abeaae8d200)

**Comment by lorenzo-deluca** [comment]
simply, with this new integration we have decided to put all the values that cannot be obtained at that time into None.

**Comment by sugar012** [comment]
> simply, with this new integration we have decided to put all the values that cannot be obtained at that time into None.

i tried re-configure the mqtt broker but same result. that's strange because some values where correct before. i think you should do the HACS integration aswell for this private server. of course for the future noobs like me.
Thanks for your time Lorenzo

**Comment by noiwid** [comment]
$SHOW should display current settings
