### ISSUE TITLE
Astra module

### ISSUE THREAD

**Issue by geozar** [lorenzo-deluca/silence-private-server#9]
Hi I have an issue with the module , I don't have access since January, I could not find a solution with local service, is there a way to test the module if it works? There is no light at the module.

**Comment by lorenzo-deluca** [comment]
mmmh, I don't know honestly.. Have you try to connect to the module on serial as described in the guide?

**Comment by geozar** [comment]
service fixed the module , was a power issue now also the app works , but i have an other issue
on Mosquitto i get this
2024-10-30 23:33:39: Connecting bridge Silence (192.168.1.64:1883)
2024-10-30 23:33:39: Client local.core-mosquitto.Silence disconnected: Broken pipe.
and on server i get this
![Screenshot 2024-10-30 233441](https://github.com/user-attachments/assets/5cf52fae-6514-4fcc-a27f-a038d2704308)

**Comment by geozar** [comment]
Hi again i fixed ( hope ) the issues with the broker but now i see these errors.

1st picture everythings is ok 
![1](https://github.com/user-attachments/assets/77d64446-ce60-4443-9b8b-7e261c302475)


but then 

![2](https://github.com/user-attachments/assets/9f4dbf96-2f05-4dda-a420-5b66b806ab03)

and

![3](https://github.com/user-attachments/assets/2028c551-c98d-454b-b936-9d27568996bb)

any thoughts?

**Comment by lorenzo-deluca** [comment]
Hi @geozar , sorry, I see now your messages ... for the first issue it's regarding MQTT authentication, but you're already fixed, good!
For the second issue, try to disable connection to Silence Server, put **bridgeMode** to false in json configuration.

It looks like the module connects correctly to your private server! :)
Maybe the Silence servers having issues...I haven't used their server in months.

Let me know  👍

**Comment by geozar** [comment]
That worked.
Thank you very much i am now fine tuning home assistant and at status i get 5.0 , 2.0 or 10.0 is it possible to change that?

![1](https://github.com/user-attachments/assets/6d86a5d2-6f08-443d-adf6-59c8695e1c80)

**Comment by lorenzo-deluca** [comment]
Good :) 

> That worked. Thank you very much i am now fine tuning home assistant and at status i get 5.0 , 2.0 or 10.0 is it possible to change that?
> 
> ![1](https://private-user-images.githubusercontent.com/98399146/384597588-6d86a5d2-6f08-443d-adf6-59c8695e1c80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTE2NTcsIm5iZiI6MTczMTI1MTM1NywicGF0aCI6Ii85ODM5OTE0Ni8zODQ1OTc1ODgtNmQ4NmE1ZDItNmYwOC00NDNkLWFkZjYtNTljODY5NWUxYzgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE1MDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZGE1ZGVlZjIzMDYyOGQyYjM4Yjc3YzVkMmUwMjA4NzBhYjEwZjAzODhiODY1NzNiMTk0ZjAyZWNjMTc2ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hk0pP4XXMVU5JhuLXb9KwcCgj_Egn_w8DfN5cOvGnQM)

Mmmh, for now you can configure a template like this

``yaml
  - platform: template
    sensors:
 
      silence_scooter_status:
        unique_id: silence_scooter_status
        value_template: >
          {% set stato = states('sensor.silence_scooter_device_silence_status') | int(default=0) %}
          {% if stato == 0 %}
            OFF
          {% elif stato == 1 %}
            BMS_ON
          {% elif stato == 2 %}
            IGNITION_ON
          {% elif stato == 3 %}
            DRIVE
          {% elif stato == 4 %}
            MOVING
          {% elif stato == 5 %}
            BATTERY_OUT
          {% elif stato == 6 %}
            CHARGING
          {% elif stato == 5 %}
            UNKNOWN
          {% endif %}
